[package]
name = "realm"
version = "1.2.1"
authors = ["zhboner <zhboner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.5", features = ["full"] }
trust-dns-resolver = "0.20"
futures = "0.3"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
